### ISSUE TITLE
Create Password

### ISSUE THREAD

**Issue by webusat** [mageprince/magento2-forcelogin#1]
Hi,

When the module is activated and I create new user in the admin, the new user cannot set their password following their password set link in the welcome email.  The link is:

http://yourdomain.com/customer/account/createPassword/?id=4&token=xxxxxxxx

I tried setting the url: http://yourdomain.com/customer/account/createPassword/ as an acceptable page but could not get it to work.

Thoughts?

Stan

**Comment by mageprince** [comment]
**@webusat** Thank you for posting issue. 
Please share configuration settings screenshot from **customers->ForceLogin->settings**

**Comment by webusat** [comment]
@mageprince 

I have since moved on to a different plugin and I do not remember my settings.  All I remember is when I received the email notifying that the account was created that I could not get access to the password reset page.  It could easily be something I did or did not do.  If you want to leave some suggestions I can look into it when I can.

Thank you so much for responding!

**Comment by mageprince** [comment]
@webusat This is has been solved.
Please change this file: **magento2-forcelogin/Helper/Data.php**

**Comment by webusat** [comment]
@mageprince 
What do I change it to?  Or do you mean to download a new copy?

**Comment by mageprince** [comment]
**@webusat** Yes download a new copy or just change this file: magento2-forcelogin/Helper/Data.php
